name: Test
on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
env:
  CI: true

jobs:
  test:
    name: "Test on Node.js ${{ matrix.node }} OS: ${{matrix.os}}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm build --all -t

      - name: Test
        run: pnpm test
